syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "razmanager/protobuf/internal/repository/crud_services/common.proto";

package razmanager.protobuf.internal.repository.crud_services.tenant;


service TenantService {
  rpc Initialize (google.protobuf.Empty) returns (TenantRead);
  rpc Read (common.IdRequest) returns (TenantReadResponse);
  rpc Create (TenantCreateUpdate) returns (common.CreateResponse);
  rpc Update (TenantUpdateRequest) returns (common.UpdateResponse);
  rpc Delete (common.DeleteRequest) returns (google.protobuf.Empty);
}


message TenantReadResponse {
  TenantRead entity = 1;
  string etag = 2;
}

message TenantRead {
  google.protobuf.StringValue id = 1;
  google.protobuf.StringValue name = 2;
  google.protobuf.StringValue description = 3;
  google.protobuf.BytesValue image = 4;
  repeated TenantInviteReadCreateUpdate tenant_invites = 6;
  repeated TenantUserReadCreateUpdate tenant_users = 7;
}


message TenantCreateUpdate {
  string name = 2;
  google.protobuf.StringValue description = 3;
  optional bytes image = 4;
  optional bool image_deleted = 5;
  repeated TenantInviteReadCreateUpdate tenant_invites = 6;
  repeated string tenant_invites_deleted = 7;
  repeated TenantUserReadCreateUpdate tenant_users = 8;
  repeated string tenant_users_deleted = 9;
}

message TenantUpdateRequest {
  string id = 1;
  TenantCreateUpdate entity = 2;
  string etag = 3;
}


message TenantInviteReadCreateUpdate {
  string id = 1;
  int32 code = 2;
  bool multiple = 3;
  google.protobuf.Timestamp time_to_live_at = 4;
}


message TenantUserReadCreateUpdate {
  string id = 1;
  google.protobuf.StringValue user_id = 2;
  google.protobuf.StringValue name = 3;
  google.protobuf.StringValue short_name = 4;
  bool administrator = 5;
}