// This is a generated file - do not edit.
//
// Generated from razmanager/protobuf/public/device_configuration_input_type_id.v1.proto.

// @dart = 3.3

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names
// ignore_for_file: curly_braces_in_flow_control_structures
// ignore_for_file: deprecated_member_use_from_same_package, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_relative_imports
// ignore_for_file: unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use deviceConfigurationInputTypeIdDescriptor instead')
const DeviceConfigurationInputTypeId$json = {
  '1': 'DeviceConfigurationInputTypeId',
  '2': [
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_START_FINISH_INDICATOR', '2': 0},
    {
      '1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_SECTOR_1_FINISH_INDICATOR',
      '2': 1
    },
    {
      '1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_SECTOR_2_FINISH_INDICATOR',
      '2': 2
    },
    {
      '1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_SPEED_TRAP_START_INDICATOR',
      '2': 3
    },
    {
      '1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_SPEED_TRAP_FINISH_INDICATOR',
      '2': 4
    },
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_EXTRA_INDICATOR', '2': 5},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_PITLANE_ENTRY', '2': 6},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_PITLANE_EXIT', '2': 7},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_PITSTOP_ENTRY', '2': 8},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_PITSTOP_EXIT', '2': 9},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_CONTROLLER_ON', '2': 10},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_CONTROLLER_BATTERY_OK', '2': 11},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_ENERGY', '2': 12},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_BRAKE', '2': 13},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_LANE_CHANGE', '2': 14},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_LANE_CHANGE_UP', '2': 15},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_LANE_CHANGE_DOWN', '2': 16},
    {
      '1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_LANE_CHANGE_DOUBLE_TAPPED',
      '2': 17
    },
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_CAR_ON_TRACK', '2': 18},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_YELLOW', '2': 19},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_RED', '2': 20},
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_POWER_OVERLOAD', '2': 21},
    {
      '1':
          'DEVICE_CONFIGURATION_INPUT_TYPE_ID_START_FINISH_INDICATOR_IGNORE_LAP_TIME',
      '2': 30
    },
    {'1': 'DEVICE_CONFIGURATION_INPUT_TYPE_ID_TAINTED', '2': 31},
  ],
};

/// Descriptor for `DeviceConfigurationInputTypeId`. Decode as a `google.protobuf.EnumDescriptorProto`.
final $typed_data.Uint8List deviceConfigurationInputTypeIdDescriptor = $convert.base64Decode(
    'Ch5EZXZpY2VDb25maWd1cmF0aW9uSW5wdXRUeXBlSWQSPQo5REVWSUNFX0NPTkZJR1VSQVRJT0'
    '5fSU5QVVRfVFlQRV9JRF9TVEFSVF9GSU5JU0hfSU5ESUNBVE9SEAASQAo8REVWSUNFX0NPTkZJ'
    'R1VSQVRJT05fSU5QVVRfVFlQRV9JRF9TRUNUT1JfMV9GSU5JU0hfSU5ESUNBVE9SEAESQAo8RE'
    'VWSUNFX0NPTkZJR1VSQVRJT05fSU5QVVRfVFlQRV9JRF9TRUNUT1JfMl9GSU5JU0hfSU5ESUNB'
    'VE9SEAISQQo9REVWSUNFX0NPTkZJR1VSQVRJT05fSU5QVVRfVFlQRV9JRF9TUEVFRF9UUkFQX1'
    'NUQVJUX0lORElDQVRPUhADEkIKPkRFVklDRV9DT05GSUdVUkFUSU9OX0lOUFVUX1RZUEVfSURf'
    'U1BFRURfVFJBUF9GSU5JU0hfSU5ESUNBVE9SEAQSNgoyREVWSUNFX0NPTkZJR1VSQVRJT05fSU'
    '5QVVRfVFlQRV9JRF9FWFRSQV9JTkRJQ0FUT1IQBRI0CjBERVZJQ0VfQ09ORklHVVJBVElPTl9J'
    'TlBVVF9UWVBFX0lEX1BJVExBTkVfRU5UUlkQBhIzCi9ERVZJQ0VfQ09ORklHVVJBVElPTl9JTl'
    'BVVF9UWVBFX0lEX1BJVExBTkVfRVhJVBAHEjQKMERFVklDRV9DT05GSUdVUkFUSU9OX0lOUFVU'
    'X1RZUEVfSURfUElUU1RPUF9FTlRSWRAIEjMKL0RFVklDRV9DT05GSUdVUkFUSU9OX0lOUFVUX1'
    'RZUEVfSURfUElUU1RPUF9FWElUEAkSNAowREVWSUNFX0NPTkZJR1VSQVRJT05fSU5QVVRfVFlQ'
    'RV9JRF9DT05UUk9MTEVSX09OEAoSPAo4REVWSUNFX0NPTkZJR1VSQVRJT05fSU5QVVRfVFlQRV'
    '9JRF9DT05UUk9MTEVSX0JBVFRFUllfT0sQCxItCilERVZJQ0VfQ09ORklHVVJBVElPTl9JTlBV'
    'VF9UWVBFX0lEX0VORVJHWRAMEiwKKERFVklDRV9DT05GSUdVUkFUSU9OX0lOUFVUX1RZUEVfSU'
    'RfQlJBS0UQDRIyCi5ERVZJQ0VfQ09ORklHVVJBVElPTl9JTlBVVF9UWVBFX0lEX0xBTkVfQ0hB'
    'TkdFEA4SNQoxREVWSUNFX0NPTkZJR1VSQVRJT05fSU5QVVRfVFlQRV9JRF9MQU5FX0NIQU5HRV'
    '9VUBAPEjcKM0RFVklDRV9DT05GSUdVUkFUSU9OX0lOUFVUX1RZUEVfSURfTEFORV9DSEFOR0Vf'
    'RE9XThAQEkAKPERFVklDRV9DT05GSUdVUkFUSU9OX0lOUFVUX1RZUEVfSURfTEFORV9DSEFOR0'
    'VfRE9VQkxFX1RBUFBFRBAREjMKL0RFVklDRV9DT05GSUdVUkFUSU9OX0lOUFVUX1RZUEVfSURf'
    'Q0FSX09OX1RSQUNLEBISLQopREVWSUNFX0NPTkZJR1VSQVRJT05fSU5QVVRfVFlQRV9JRF9ZRU'
    'xMT1cQExIqCiZERVZJQ0VfQ09ORklHVVJBVElPTl9JTlBVVF9UWVBFX0lEX1JFRBAUEjUKMURF'
    'VklDRV9DT05GSUdVUkFUSU9OX0lOUFVUX1RZUEVfSURfUE9XRVJfT1ZFUkxPQUQQFRJNCklERV'
    'ZJQ0VfQ09ORklHVVJBVElPTl9JTlBVVF9UWVBFX0lEX1NUQVJUX0ZJTklTSF9JTkRJQ0FUT1Jf'
    'SUdOT1JFX0xBUF9USU1FEB4SLgoqREVWSUNFX0NPTkZJR1VSQVRJT05fSU5QVVRfVFlQRV9JRF'
    '9UQUlOVEVEEB8=');
