syntax = "proto3";

import "google/protobuf/duration.proto";
import "google/protobuf/wrappers.proto";

package razmanager.protobuf.public.v1;



enum DetailStateTypeId {
  DETAIL_STATE_TYPE_ID_PENDING = 0;
  DETAIL_STATE_TYPE_ID_OPENED = 1;
  DETAIL_STATE_TYPE_ID_COUNTDOWN = 2;
  DETAIL_STATE_TYPE_ID_RUNNING = 3;
  DETAIL_STATE_TYPE_ID_YELLOW = 4;
  DETAIL_STATE_TYPE_ID_COUNTDOWN_YELLOW = 5;
  DETAIL_STATE_TYPE_ID_RED = 6;
  DETAIL_STATE_TYPE_ID_COUNTDOWN_RED = 7;
  DETAIL_STATE_TYPE_ID_ENDED = 8;
  DETAIL_STATE_TYPE_ID_OFF = 9;
  DETAIL_STATE_TYPE_ID_CLOSED = 10;
}


message DetailStateType {
  DetailStateTypeId id = 1;
  string name = 2;
}


message DetailState {
  DetailStateType detail_state_type = 1;
  google.protobuf.UInt32Value laps_current = 2;
  bool timer_is_running = 3;
  google.protobuf.Duration timer_elapsed = 4;
  uint32 start_light_id = 5;
}