syntax = "proto3";

package razmanager.protobuf.public.v1;


enum DeviceConfigurationFeatureTypeId {
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_UNDEFINED = 0;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_SECTOR_1 = 1;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_SECTOR_2 = 2;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_SECTOR_3 = 3;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_SPEED_TRAP = 4;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_PITLANE = 5;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_PITSTOP = 6;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_ENERGY = 7; 
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_CAR_ON_TRACK = 8;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_LANE_BASED_ID = 9;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_CONTROLLER_BASED_ID = 10;
  DEVICE_CONFIGURATION_FEATURE_TYPE_ID_THROTTLE_PROFILES = 11;
}
