syntax = "proto3";

import "google/protobuf/empty.proto";
import "razmanager/protobuf/public/device.v1.proto";
import "razmanager/protobuf/public/device_request_response.v1.proto";

package razmanager.protobuf.public.v1;


service DeviceService {
  rpc DeviceInformation (public.v1.DeviceInformation) returns (google.protobuf.Empty);
  rpc DeviceRequestResponse (stream DeviceRequest) returns (stream DeviceResponse);
  rpc DeviceResponseRequest (stream DeviceResponse) returns (stream DeviceRequest);
}