syntax = "proto3";

package razmanager.protobuf.public.v1;


enum DeviceConfigurationInputTypeId {
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_START_FINISH_INDICATOR = 0;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_SECTOR_1_FINISH_INDICATOR = 1;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_SECTOR_2_FINISH_INDICATOR = 2;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_SPEED_TRAP_START_INDICATOR = 3;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_SPEED_TRAP_FINISH_INDICATOR = 4;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_EXTRA_INDICATOR = 5;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_PITLANE_ENTRY = 6;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_PITLANE_EXIT = 7;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_PITSTOP_ENTRY = 8;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_PITSTOP_EXIT = 9;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_CONTROLLER_ON = 10;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_CONTROLLER_BATTERY_OK = 11;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_ENERGY = 12;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_BRAKE = 13;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_LANE_CHANGE = 14;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_LANE_CHANGE_UP = 15;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_LANE_CHANGE_DOWN = 16;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_LANE_CHANGE_DOUBLE_TAPPED = 17;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_CAR_ON_TRACK = 18;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_YELLOW = 19;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_RED = 20;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_POWER_OVERLOAD = 21;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_START_FINISH_INDICATOR_IGNORE_LAP_TIME = 30;
  DEVICE_CONFIGURATION_INPUT_TYPE_ID_TAINTED = 31;
}
