syntax = "proto3";

package razmanager.protobuf.public.v1;


enum DeviceConfigurationOutputTypeId {
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_START_FINISH_INDICATOR = 0;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_POWER_ON = 1;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_POWER_YELLOW = 2;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_POWER_OFF = 3;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_COUNTDOWN_ON = 4;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_COUNTDOWN_OFF = 5;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_HEAT_GREEN = 6;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_HEAT_YELLOW = 7;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_HEAT_RED = 8;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_HEAT_OFF = 9;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_PITSTOP = 10;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_ENERGY_LEVEL = 11;
  DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_ENERGY_LAPS_LEFT = 12;
  //DEVICE_OUTPUT_TYPE_ID_EXTRA_INDICATOR = 12;
  //DEVICE_CONFIGURATION_OUTPUT_TYPE_ID_EVENT_DATA = 13;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_A = 20;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_B = 21;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_C = 22;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_D = 23;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_E = 24;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_R1 = 25;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_G1 = 26;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_B1 = 27;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_R2 = 28;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_G2 = 29;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_B2 = 30;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_OE = 31;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_CLK = 32;
  //DEVICE_OUTPUT_TYPE_RGB_LED_MATRIX_LAT = 33;
}
