syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "razmanager/protobuf/public/heat.v1.proto";

package razmanager.protobuf.public.v1;


service HeatService {
  rpc Subscribe (google.protobuf.StringValue) returns (stream Heat);
  rpc HeatStateSubscribe (google.protobuf.StringValue) returns (stream HeatState);
  rpc HeatLeaderboardSubscribe (google.protobuf.StringValue) returns (stream HeatLeaderboard);
  rpc HeatAnalysesSubscribe (google.protobuf.StringValue) returns (stream HeatAnalyses);
  rpc HeatStintAnalysesSubscribe (HeatStintAnalysesRequest) returns (stream HeatStintAnalysis);
  rpc Command (HeatCommandRequest) returns (google.protobuf.Empty);
  rpc CommandPermissions (google.protobuf.StringValue) returns (HeatCommandPermissions);
}

message HeatCommandRequest {
  string id = 1;
  HeatCommandTypeId heat_command_type_id = 2;
}

message HeatStintAnalysesRequest {
  string heat_id = 1;
  uint32 indicator_id = 2;
}