syntax = "proto3";

import "google/protobuf/wrappers.proto";
import "razmanager/protobuf/public/summary_state_type_id.v1.proto";
import "razmanager/protobuf/public/indicator_flag_id.v1.proto";
import "razmanager/protobuf/public/indicator_time_type_id.v1.proto";
import "razmanager/protobuf/public/stint.v1.proto";

package razmanager.protobuf.public.v1;


message HeatWithStints {
  string id = 1;
  string race_session_id = 2;
  uint32 number = 4;
  google.protobuf.StringValue name = 5;
  repeated Stint stints = 6;
  SummaryStateType state_type = 7;
}


message HeatWithStintsState {
  SummaryStateType state_type = 2;
  repeated HeatWithStintsEventUserState heat_with_stints_event_user_states = 3;
  Stint current_stint = 6;
}

message HeatWithStintsEventUserState {
  string event_user_id = 1;
  google.protobuf.UInt32Value indicator_id_current = 2;
  repeated uint32 indicator_ids_finished = 3;
}


message HeatWithStintsLeaderboard {
  google.protobuf.StringValue correlation_id = 1;
  repeated HeatWithStintsLeaderboardEventUser event_users = 2;
}


message HeatWithStintsLeaderboardEventUser {
  string event_user_id = 1;
  google.protobuf.UInt32Value indicator_id = 2;
  uint32 position = 3;
  //uint32 position_estimate = 3;
  google.protobuf.StringValue laps_completed = 4;
  google.protobuf.StringValue laps_predicted = 5;
  //google.protobuf.UInt32Value points = 6;
  //google.protobuf.UInt32Value points_predicted = 7;
  repeated IndicatorTimeTypeTime time_type_times = 6;
  google.protobuf.StringValue gap_laps_predicted_leader = 8;
  google.protobuf.StringValue gap_laps_predicted_interval = 9;
  google.protobuf.DoubleValue gap_laps_predicted_interval_fraction = 10;

  uint32 energy_percent = 11;
  google.protobuf.UInt32Value energy_laps_left = 12;

  repeated IndicatorFlag flags = 13;
  uint32 pit_lanes = 14;
  uint32 car_off_tracks = 15;
  
  google.protobuf.StringValue team_event_user_id = 16;
}