syntax = "proto3";

import "google/protobuf/wrappers.proto";
import "razmanager/protobuf/public/indicator_flag_id.v1.proto";

package razmanager.protobuf.public.v1;


enum RaceSessionTypeId {
  RACE_SESSION_TYPE_ID_WITHOUT_STINT = 0;
  RACE_SESSION_TYPE_ID_WITH_STINT = 1;
}


message RaceSessionLeaderboard {
  repeated RaceSessionLeaderboardEventUser event_users = 2;
}


message RaceSessionLeaderboardEventUser {
  string event_user_id = 1;
  uint32 position = 2;
  //uint32 position_estimate = 3;
  google.protobuf.StringValue laps_completed = 4;
  google.protobuf.StringValue laps_predicted = 5;
  //google.protobuf.UInt32Value points = 6;
  //google.protobuf.UInt32Value points_predicted = 7;
  google.protobuf.StringValue gap_laps_predicted_leader = 8;
  google.protobuf.StringValue gap_laps_predicted_interval = 9;
  google.protobuf.DoubleValue gap_laps_predicted_interval_fraction = 10;

  repeated IndicatorFlag flags = 11;

  //uint32 pit_lanes = 10;
  //uint32 car_off_tracks = 11;
  google.protobuf.StringValue team_event_user_id = 12;
}