syntax = "proto3";

import "google/protobuf/duration.proto";
import "google/protobuf/wrappers.proto";
import "razmanager/protobuf/public/track_configuration.v1.proto";
import "razmanager/protobuf/public/race_feature_type_id.v1.proto";
import "razmanager/protobuf/public/heat.v1.proto";

package razmanager.protobuf.public.v1;


enum RaceCommandTypeId {
  RACE_COMMAND_TYPE_ID_START = 0;
  RACE_COMMAND_TYPE_ID_PAUSE = 1;
  RACE_COMMAND_TYPE_ID_END = 2;
  RACE_COMMAND_TYPE_ID_RESET = 3;
}

message RaceCommandPermissions {
  repeated RaceCommandTypeId items = 1;
}


enum RaceStateTypeId {
  RACE_STATE_TYPE_ID_PENDING = 0;
  RACE_STATE_TYPE_ID_STARTED = 1;
  RACE_STATE_TYPE_ID_PAUSED = 2;
  RACE_STATE_TYPE_ID_ENDED = 3;
}


message RaceStateType {
  RaceStateTypeId id = 1;
  string name = 2;
}


message Race {
  string id = 1;
  uint32 number = 2;
  google.protobuf.StringValue name = 3;
  string event_id = 4;
  TrackConfiguration track_configuration = 5;
  google.protobuf.StringValue points_scheme_id = 6;
  bool practice_session = 7;
  bool qualifying_session = 8;
  bool race_session = 9;
  HeatEndTypeId race_heat_end_type_id = 10;
  google.protobuf.UInt32Value race_heat_end_lap_laps = 11;
  google.protobuf.Duration race_heat_end_duration_duration = 12;
  RaceStateType race_state_type = 13;
  repeated RaceFeatureTypeId race_features = 14;
  repeated Heat heats = 15;
}


message RaceLeaderboard {
  repeated RaceLeaderboardEventUser event_users = 1;
}


message RaceLeaderboardEventUser {
  string event_user_id = 1;
  google.protobuf.UInt32Value position = 2;
  //uint32 position_estimate = 3;
  google.protobuf.DoubleValue laps = 4;
  google.protobuf.DoubleValue laps_estimate = 5;
  google.protobuf.UInt32Value points = 6;
  google.protobuf.UInt32Value points_estimate = 7;
  google.protobuf.StringValue gap_leader = 8;
  google.protobuf.StringValue gap_interval = 9;
  google.protobuf.DoubleValue gap_interval_fraction = 10;

  repeated HeatIndicatorFlag flags = 11;

  //uint32 pit_lanes = 10;
  //uint32 car_off_tracks = 11;
}

message RaceLeaderboardEventUserHeatUpdate {
  string event_user_id = 1;
  //google.protobuf.UInt32Value position = 2;
  //uint32 position_estimate = 3;
  google.protobuf.DoubleValue laps = 4;
  //google.protobuf.DoubleValue laps_estimate = 5;
  //google.protobuf.UInt32Value points = 6;
  //google.protobuf.UInt32Value points_estimate = 7;
  //google.protobuf.StringValue gap_leader = 8;
  //google.protobuf.StringValue gap_interval = 9;
  //google.protobuf.DoubleValue gap_interval_fraction = 10;

  repeated HeatIndicatorFlag flags = 11;

  //uint32 pit_lanes = 10;
  //uint32 car_off_tracks = 11;
}
