syntax = "proto3";

package razmanager.protobuf.public.v1;


enum RaceFeatureTypeId {
  RACE_FEATURE_TYPE_ID_UNDEFINED = 0;
  RACE_FEATURE_TYPE_ID_SECTOR_1 = 1;
  RACE_FEATURE_TYPE_ID_SECTOR_2 = 2;
  RACE_FEATURE_TYPE_ID_SECTOR_3 = 3;
  RACE_FEATURE_TYPE_ID_SPEED_TRAP = 4;
  RACE_FEATURE_TYPE_ID_PITLANE = 5;
  RACE_FEATURE_TYPE_ID_PITSTOP = 6;
  RACE_FEATURE_TYPE_ID_ENERGY = 7; 
  RACE_FEATURE_TYPE_ID_CAR_ON_TRACK = 8;
  RACE_FEATURE_TYPE_ID_LANE_BASED_ID = 9;
  RACE_FEATURE_TYPE_ID_CONTROLLER_BASED_ID = 10;
  RACE_FEATURE_TYPE_ID_THROTTLE_PROFILES = 11;  
}
