syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "razmanager/protobuf/public/summary_state_type_id.v1.proto";
import "razmanager/protobuf/public/heat_with_stint.v1.proto";

package razmanager.protobuf.internal.repository.system_services.heat_with_stint;


service HeatWithStintService {
  rpc Read (google.protobuf.StringValue) returns (public.v1.HeatWithStint);
  rpc UpdateState (HeatWithStintStateUpdateRequest) returns (google.protobuf.Empty);
}


message HeatWithStintStateUpdateRequest {
  string id = 1;
  public.v1.SummaryStateTypeId heat_with_stint_state_type_id = 2;
}