syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "razmanager/protobuf/public/summary_state_type_id.v1.proto";
import "razmanager/protobuf/public/race.v1.proto";

package razmanager.protobuf.internal.repository.system_services.race;


service RaceService {
  rpc Read (google.protobuf.StringValue) returns (public.v1.Race);
  rpc UpdateState (RaceStateUpdateRequest) returns (google.protobuf.Empty);
}


message RaceStateUpdateRequest {
  string id = 1;
  public.v1.SummaryStateTypeId race_state_type_id = 2;
}