syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/wrappers.proto";
import "razmanager/protobuf/public/summary_state_type_id.v1.proto";
import "razmanager/protobuf/public/race_session_with_stints.v1.proto";

package razmanager.protobuf.internal.repository.system_services.race_session_with_stints;


service RaceSessionWithStintsService {
  rpc Read (google.protobuf.StringValue) returns (public.v1.RaceSessionWithStints);
  rpc UpdateState (RaceSessionWithStintsStateUpdateRequest) returns (google.protobuf.Empty);
}


message RaceSessionWithStintsStateUpdateRequest {
  string id = 1;
  public.v1.SummaryStateTypeId state_type_id = 2;
}