//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazManager.IO.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GpioInputType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GpioInputType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RazManager.IO.Utilities.GpioInputType", typeof(GpioInputType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitstop entry.
        /// </summary>
        public static string PitstopEntry {
            get {
                return ResourceManager.GetString("PitstopEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitstop exit.
        /// </summary>
        public static string PitstopExit {
            get {
                return ResourceManager.GetString("PitstopExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power overload.
        /// </summary>
        public static string PowerOverload {
            get {
                return ResourceManager.GetString("PowerOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red flag.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector 1 finish indicator.
        /// </summary>
        public static string Sector1FinishIndicator {
            get {
                return ResourceManager.GetString("Sector1FinishIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector 2 finish indicator.
        /// </summary>
        public static string Sector2FinishIndicator {
            get {
                return ResourceManager.GetString("Sector2FinishIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed trap finish indicator.
        /// </summary>
        public static string SpeedTrapFinishIndicator {
            get {
                return ResourceManager.GetString("SpeedTrapFinishIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed trap start indicator.
        /// </summary>
        public static string SpeedTrapStartIndicator {
            get {
                return ResourceManager.GetString("SpeedTrapStartIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/finish indicator.
        /// </summary>
        public static string StartFinishIndicator {
            get {
                return ResourceManager.GetString("StartFinishIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow flag.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
