//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazManager.IO.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GpioOutputType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GpioOutputType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RazManager.IO.Utilities.GpioOutputType", typeof(GpioOutputType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown off.
        /// </summary>
        public static string CountdownOff {
            get {
                return ResourceManager.GetString("CountdownOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countdown on.
        /// </summary>
        public static string CountdownOn {
            get {
                return ResourceManager.GetString("CountdownOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy level.
        /// </summary>
        public static string EnergyLevel {
            get {
                return ResourceManager.GetString("EnergyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat green.
        /// </summary>
        public static string HeatGreen {
            get {
                return ResourceManager.GetString("HeatGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat off.
        /// </summary>
        public static string HeatOff {
            get {
                return ResourceManager.GetString("HeatOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat red.
        /// </summary>
        public static string HeatRed {
            get {
                return ResourceManager.GetString("HeatRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat yellow.
        /// </summary>
        public static string HeatYellow {
            get {
                return ResourceManager.GetString("HeatYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitstop.
        /// </summary>
        public static string Pitstop {
            get {
                return ResourceManager.GetString("Pitstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power off.
        /// </summary>
        public static string PowerOff {
            get {
                return ResourceManager.GetString("PowerOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power on.
        /// </summary>
        public static string PowerOn {
            get {
                return ResourceManager.GetString("PowerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power slow.
        /// </summary>
        public static string PowerYellow {
            get {
                return ResourceManager.GetString("PowerYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix A.
        /// </summary>
        public static string RgbLedMatrixA {
            get {
                return ResourceManager.GetString("RgbLedMatrixA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix B.
        /// </summary>
        public static string RgbLedMatrixB {
            get {
                return ResourceManager.GetString("RgbLedMatrixB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix B1.
        /// </summary>
        public static string RgbLedMatrixB1 {
            get {
                return ResourceManager.GetString("RgbLedMatrixB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix B2.
        /// </summary>
        public static string RgbLedMatrixB2 {
            get {
                return ResourceManager.GetString("RgbLedMatrixB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix C.
        /// </summary>
        public static string RgbLedMatrixC {
            get {
                return ResourceManager.GetString("RgbLedMatrixC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix CLK.
        /// </summary>
        public static string RgbLedMatrixClk {
            get {
                return ResourceManager.GetString("RgbLedMatrixClk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix D.
        /// </summary>
        public static string RgbLedMatrixD {
            get {
                return ResourceManager.GetString("RgbLedMatrixD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix E.
        /// </summary>
        public static string RgbLedMatrixE {
            get {
                return ResourceManager.GetString("RgbLedMatrixE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix G1.
        /// </summary>
        public static string RgbLedMatrixG1 {
            get {
                return ResourceManager.GetString("RgbLedMatrixG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix G2.
        /// </summary>
        public static string RgbLedMatrixG2 {
            get {
                return ResourceManager.GetString("RgbLedMatrixG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix LAT.
        /// </summary>
        public static string RgbLedMatrixLat {
            get {
                return ResourceManager.GetString("RgbLedMatrixLat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix OE.
        /// </summary>
        public static string RgbLedMatrixOe {
            get {
                return ResourceManager.GetString("RgbLedMatrixOe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix R1.
        /// </summary>
        public static string RgbLedMatrixR1 {
            get {
                return ResourceManager.GetString("RgbLedMatrixR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB LED matrix R2.
        /// </summary>
        public static string RgbLedMatrixR2 {
            get {
                return ResourceManager.GetString("RgbLedMatrixR2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/finish indicator.
        /// </summary>
        public static string StartFinishIndicator {
            get {
                return ResourceManager.GetString("StartFinishIndicator", resourceCulture);
            }
        }
    }
}
