// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RazManager.Silo.Repository.Stores.Context;

#nullable disable

namespace RazManager.Silo.Repository.Migrations
{
    [DbContext(typeof(SiloDbContext))]
    [Migration("20260105084046_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RazManager.Silo.Repository.Stores.Entities.GrainStorage.GrainStorageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("GrainId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("State")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("TimeToLiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "StateName", "GrainId")
                        .IsUnique();

                    b.ToTable("GrainStorage");
                });

            modelBuilder.Entity("RazManager.Silo.Repository.Stores.Entities.Membership.MembershipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("IAmAliveTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MembershipVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProxyPort")
                        .HasColumnType("integer");

                    b.Property<string>("SiloAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SiloName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MembershipVersionId", "SiloAddress")
                        .IsUnique();

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("RazManager.Silo.Repository.Stores.Entities.MembershipSuspectTime.MembershipSuspectTimeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("SiloAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("SuspectTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId", "SiloAddress")
                        .IsUnique();

                    b.ToTable("MembershipSuspectTimes");
                });

            modelBuilder.Entity("RazManager.Silo.Repository.Stores.Entities.MembershipVersion.MembershipVersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .IsUnique();

                    b.ToTable("MembershipVersions");
                });

            modelBuilder.Entity("RazManager.Silo.Repository.Stores.Entities.Reminder.ReminderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClusterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("GrainId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Period")
                        .HasColumnType("interval");

                    b.Property<string>("ReminderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "GrainId", "ReminderName")
                        .IsUnique();

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("RazManager.Silo.Repository.Stores.Entities.Membership.MembershipEntity", b =>
                {
                    b.HasOne("RazManager.Silo.Repository.Stores.Entities.MembershipVersion.MembershipVersionEntity", "MembershipVersion")
                        .WithMany("Memberships")
                        .HasForeignKey("MembershipVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipVersion");
                });

            modelBuilder.Entity("RazManager.Silo.Repository.Stores.Entities.MembershipSuspectTime.MembershipSuspectTimeEntity", b =>
                {
                    b.HasOne("RazManager.Silo.Repository.Stores.Entities.Membership.MembershipEntity", "Membership")
                        .WithMany("MembershipSuspectTimes")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("RazManager.Silo.Repository.Stores.Entities.Membership.MembershipEntity", b =>
                {
                    b.Navigation("MembershipSuspectTimes");
                });

            modelBuilder.Entity("RazManager.Silo.Repository.Stores.Entities.MembershipVersion.MembershipVersionEntity", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
