//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazManager.Repository.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DeviceInputType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeviceInputType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RazManager.Repository.Resources.DeviceInputType", typeof(DeviceInputType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake button.
        /// </summary>
        public static string Brake {
            get {
                return ResourceManager.GetString("Brake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car is on the track.
        /// </summary>
        public static string CarOnTrack {
            get {
                return ResourceManager.GetString("CarOnTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller battery OK.
        /// </summary>
        public static string ControllerBatteryOk {
            get {
                return ResourceManager.GetString("ControllerBatteryOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller on.
        /// </summary>
        public static string ControllerOn {
            get {
                return ResourceManager.GetString("ControllerOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        public static string Energy {
            get {
                return ResourceManager.GetString("Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra function indicator.
        /// </summary>
        public static string ExtraIndicator {
            get {
                return ResourceManager.GetString("ExtraIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane change button.
        /// </summary>
        public static string LaneChange {
            get {
                return ResourceManager.GetString("LaneChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane change button double tapped.
        /// </summary>
        public static string LaneChangeDoubleTapped {
            get {
                return ResourceManager.GetString("LaneChangeDoubleTapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane change down button.
        /// </summary>
        public static string LaneChangeDown {
            get {
                return ResourceManager.GetString("LaneChangeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lane change up button.
        /// </summary>
        public static string LaneChangeUp {
            get {
                return ResourceManager.GetString("LaneChangeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitlane entry.
        /// </summary>
        public static string PitlaneEntry {
            get {
                return ResourceManager.GetString("PitlaneEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitlane exit.
        /// </summary>
        public static string PitlaneExit {
            get {
                return ResourceManager.GetString("PitlaneExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitstop entry.
        /// </summary>
        public static string PitstopEntry {
            get {
                return ResourceManager.GetString("PitstopEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitstop exit.
        /// </summary>
        public static string PitstopExit {
            get {
                return ResourceManager.GetString("PitstopExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power overload.
        /// </summary>
        public static string PowerOverload {
            get {
                return ResourceManager.GetString("PowerOverload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red flag.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector 1 finish indicator.
        /// </summary>
        public static string Sector1FinishIndicator {
            get {
                return ResourceManager.GetString("Sector1FinishIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector 2 finish indicator.
        /// </summary>
        public static string Sector2FinishIndicator {
            get {
                return ResourceManager.GetString("Sector2FinishIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed trap finish indicator.
        /// </summary>
        public static string SpeedTrapFinishIndicator {
            get {
                return ResourceManager.GetString("SpeedTrapFinishIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed trap start indicator.
        /// </summary>
        public static string SpeedTrapStartIndicator {
            get {
                return ResourceManager.GetString("SpeedTrapStartIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/finish indicator.
        /// </summary>
        public static string StartFinishIndicator {
            get {
                return ResourceManager.GetString("StartFinishIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow flag.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
