//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazManager.Repository.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RaceFormatType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RaceFormatType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RazManager.Repository.Resources.RaceFormatType", typeof(RaceFormatType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drivers race against all other drivers on all (selected) lanes (suitable for 2-lane analog tracks only).
        /// </summary>
        public static string AllDriversAllLanesAllDrivers {
            get {
                return ResourceManager.GetString("AllDriversAllLanesAllDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drivers race once on all (selected) lanes, and typically move to the next lane in the next heat (suitable for analog tracks only).
        /// </summary>
        public static string AllDriversAllLanesNext {
            get {
                return ResourceManager.GetString("AllDriversAllLanesNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drivers race once on all (selected) lanes, and race against as many other drivers as possible (suitable for analog tracks only).
        /// </summary>
        public static string AllDriversAllLanesSpread {
            get {
                return ResourceManager.GetString("AllDriversAllLanesSpread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drivers race using their own controller# only (suitable for digital tracks only).
        /// </summary>
        public static string AllDriversUniqueController {
            get {
                return ResourceManager.GetString("AllDriversUniqueController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step up.
        /// </summary>
        public static string StepUp {
            get {
                return ResourceManager.GetString("StepUp", resourceCulture);
            }
        }
    }
}
