<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="HeatStateType.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>HeatStateType.resx</DependentUpon>
    </Compile>
    <Compile Update="RaceStateType.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>RaceStateType.resx</DependentUpon>
    </Compile>
    <Compile Update="SessionType.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SessionType.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="HeatStateType.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>HeatStateType.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="RaceStateType.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>RaceStateType.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="SessionType.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>SessionType.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
