// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RazManager.Repository.Stores.Context;

#nullable disable

namespace RazManager.Repository.Migrations
{
    [DbContext(typeof(RepositoryDbContext))]
    [Migration("20260323110527_preconfiguredStint")]
    partial class preconfiguredStint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Autopilot.AutopilotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("TrackConfigurationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackConfigurationId", "Name")
                        .IsUnique();

                    b.ToTable("Autopilots");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.AutopilotImage.AutopilotImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AutopilotId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AutopilotId", "ImageSize")
                        .IsUnique();

                    b.ToTable("AutopilotImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Car.CarEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.CarCarTag.CarCarTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarTagId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId", "CarTagId")
                        .IsUnique();

                    b.HasIndex("CarTagId", "CarId")
                        .IsUnique();

                    b.ToTable("CarCarTags");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.CarImage.CarImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CarId", "ImageSize")
                        .IsUnique();

                    b.ToTable("CarImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.CarTag.CarTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte>("Position")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.HasIndex("TenantId", "Position", "Name")
                        .IsUnique();

                    b.ToTable("CarTags");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Device.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Simulated")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.DeviceConfiguration.DeviceConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Name")
                        .IsUnique();

                    b.ToTable("DeviceConfigurations");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.DeviceConfigurationFeature.DeviceConfigurationFeatureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceConfigurationFeatureTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceConfigurationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceConfigurationId", "DeviceConfigurationFeatureTypeId")
                        .IsUnique();

                    b.ToTable("DeviceConfigurationFeatures");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.DeviceConfigurationInput.DeviceConfigurationInputEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<byte?>("DeviceConfigurationInputId")
                        .HasColumnType("smallint");

                    b.Property<byte?>("DeviceConfigurationInputSubId")
                        .HasColumnType("smallint");

                    b.Property<string>("DeviceConfigurationInputTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceConfigurationId");

                    b.ToTable("DeviceConfigurationInputs");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.DeviceConfigurationOutput.DeviceConfigurationOutputEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<byte?>("DeviceConfigurationOutputId")
                        .HasColumnType("smallint");

                    b.Property<string>("DeviceConfigurationOutputTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeviceConfigurationId");

                    b.ToTable("DeviceConfigurationOutputs");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Event.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentHeatId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CurrentRaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("EventVisibilityTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("PublishFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeToLiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TimeToLiveAt");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Events");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.EventImage.EventImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "ImageSize")
                        .IsUnique();

                    b.ToTable("EventImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.EventInvite.EventInviteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Multiple")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("TimeToLiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("EventId");

                    b.HasIndex("TimeToLiveAt");

                    b.ToTable("EventInvites");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.EventUser.EventUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AutopilotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventUserTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AutopilotId");

                    b.HasIndex("EventId");

                    b.HasIndex("EventUserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventUsers");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.EventUserImage.EventUserImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventUserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventUserId", "ImageSize")
                        .IsUnique();

                    b.ToTable("EventUserImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Heat.HeatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("PreconfiguredIndicatorsJson")
                        .HasColumnType("text");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SessionTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RaceId", "SessionTypeId", "Number")
                        .IsUnique();

                    b.ToTable("Heats");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.HeatIndicator.HeatIndicatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CarClassColor")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeatId")
                        .HasColumnType("uuid");

                    b.Property<long>("IndicatorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("EventUserId");

                    b.HasIndex("HeatId", "EventUserId")
                        .IsUnique();

                    b.HasIndex("HeatId", "IndicatorId")
                        .IsUnique();

                    b.ToTable("HeatIndicators");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.HeatIndicatorStint.HeatIndicatorStintEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeatIndicatorId")
                        .HasColumnType("uuid");

                    b.Property<long>("Lap")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EventUserId");

                    b.HasIndex("HeatIndicatorId", "Lap")
                        .IsUnique();

                    b.ToTable("HeatIndicatorStints");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.HeatJournal.HeatJournalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeatId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HeatId", "Timestamp", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("HeatJournals");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.PointsScheme.PointsSchemeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<byte>("MaxDrivers")
                        .HasColumnType("smallint");

                    b.Property<byte>("MinDrivers")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte?>("PointsRaceSessionHeatFastestLap")
                        .HasColumnType("smallint");

                    b.Property<byte?>("PointsRaceSessionHeatLedAtLeastOneLap")
                        .HasColumnType("smallint");

                    b.Property<byte?>("PointsRaceSessionHeatMostLedLaps")
                        .HasColumnType("smallint");

                    b.Property<byte?>("PointsRaceSessionOverallFastestLap")
                        .HasColumnType("smallint");

                    b.Property<byte?>("PointsRaceSessionOverallMostLedLaps")
                        .HasColumnType("smallint");

                    b.Property<byte>("Position")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("PointsSchemas");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.PointsSchemePosition.PointsSchemePositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte>("Points")
                        .HasColumnType("smallint");

                    b.Property<Guid>("PointsSchemeId")
                        .HasColumnType("uuid");

                    b.Property<byte>("Position")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("PointsSchemeId", "Position")
                        .IsUnique();

                    b.ToTable("PointsSchemePositions");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Race.RaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<bool>("EnergySimulation")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("HeatCarTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PointsSchemeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PracticeSession")
                        .HasColumnType("boolean");

                    b.Property<bool>("QualifyingSession")
                        .HasColumnType("boolean");

                    b.Property<string>("RaceFormatTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("RaceHeatEndDurationDuration")
                        .HasColumnType("interval");

                    b.Property<int?>("RaceHeatEndLapLaps")
                        .HasColumnType("integer");

                    b.Property<string>("RaceHeatEndTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RaceSession")
                        .HasColumnType("boolean");

                    b.Property<string>("RaceStateTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrackConfigurationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PointsSchemeId");

                    b.HasIndex("TrackConfigurationId");

                    b.HasIndex("EventId", "Number")
                        .IsUnique();

                    b.ToTable("Races");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.RaceCarTag.RaceCarTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CarTagId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarTagId");

                    b.HasIndex("RaceId", "CarTagId")
                        .IsUnique();

                    b.ToTable("RaceCarTagEntity");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.RaceEventUser.RaceEventUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("EventUserId");

                    b.HasIndex("RaceId", "EventUserId")
                        .IsUnique();

                    b.ToTable("RaceEventUsers");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.RaceIndicator.RaceIndicatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uuid");

                    b.Property<long>("IndicatorId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("RaceId", "IndicatorId")
                        .IsUnique();

                    b.ToTable("RaceIndicators");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.RaceIndicatorEventUser.RaceIndicatorEventUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("CarClassColor")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EventUserId")
                        .HasColumnType("uuid");

                    b.Property<long>("IndicatorId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("EventUserId");

                    b.HasIndex("RaceId", "EventUserId")
                        .IsUnique();

                    b.HasIndex("RaceId", "IndicatorId")
                        .IsUnique();

                    b.ToTable("RaceIndicatorEventUsers");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TenantImage.TenantImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ImageSize")
                        .IsUnique();

                    b.ToTable("TenantImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TenantInvite.TenantInviteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<bool>("Multiple")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimeToLiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.HasIndex("TimeToLiveAt");

                    b.ToTable("TenantInvites");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TenantUser.TenantUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Administrator")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortName")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("TenantUsers");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Track.TrackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackConfiguration.TrackConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("LaptimeMaxSeconds")
                        .HasColumnType("smallint");

                    b.Property<byte>("LaptimeMinSeconds")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "Name")
                        .IsUnique();

                    b.ToTable("TrackConfigurations");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackConfigurationDeviceConfiguration.TrackConfigurationDeviceConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackConfigurationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeviceConfigurationId", "TrackConfigurationId")
                        .IsUnique();

                    b.HasIndex("TrackConfigurationId", "DeviceConfigurationId")
                        .IsUnique();

                    b.ToTable("TrackConfigurationDeviceConfigurations");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackConfigurationIndicator.TrackConfigurationIndicatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("Color")
                        .HasColumnType("bigint");

                    b.Property<byte>("IndicatorId")
                        .HasColumnType("smallint");

                    b.Property<Guid>("TrackConfigurationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackConfigurationId", "IndicatorId")
                        .IsUnique();

                    b.ToTable("TrackConfigurationIndicators");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackConfigurationRaceFormat.TrackConfigurationRaceFormatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("RaceFormatTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrackConfigurationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackConfigurationId", "RaceFormatTypeId")
                        .IsUnique();

                    b.ToTable("TrackConfigurationRaceFormats");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackImage.TrackImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackId", "ImageSize")
                        .IsUnique();

                    b.ToTable("TrackImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.User.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Administrator")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ETag")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("TimeToLiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TimeToLiveAt");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.UserImage.UserImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ImageSize")
                        .IsUnique();

                    b.ToTable("UserImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Version.VersionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<short>("Major")
                        .HasColumnType("smallint");

                    b.Property<short>("Minor")
                        .HasColumnType("smallint");

                    b.Property<short>("Patch")
                        .HasColumnType("smallint");

                    b.Property<bool>("Valid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Major", "Minor", "Patch")
                        .IsUnique();

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.VersionNote.VersionNoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte>("Position")
                        .HasColumnType("smallint");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "Position")
                        .IsUnique();

                    b.ToTable("VersionNotes");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.VersionPlatform.VersionPlatformEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("VersionPlatformId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VersionId", "VersionPlatformId")
                        .IsUnique();

                    b.ToTable("VersionPlatforms");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Autopilot.AutopilotEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.TrackConfiguration.TrackConfigurationEntity", "TrackConfiguration")
                        .WithMany()
                        .HasForeignKey("TrackConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackConfiguration");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.AutopilotImage.AutopilotImageEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Autopilot.AutopilotEntity", "Autopilot")
                        .WithMany("AutopilotImages")
                        .HasForeignKey("AutopilotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autopilot");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Car.CarEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.CarCarTag.CarCarTagEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Car.CarEntity", "Car")
                        .WithMany("CarCarTags")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazManager.Repository.Stores.Entities.CarTag.CarTagEntity", "CarTag")
                        .WithMany("CarCarTags")
                        .HasForeignKey("CarTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("CarTag");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.CarImage.CarImageEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Car.CarEntity", "Car")
                        .WithMany("CarImages")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.CarTag.CarTagEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Device.DeviceEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.DeviceConfiguration.DeviceConfigurationEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Device.DeviceEntity", "Device")
                        .WithMany("DeviceConfigurations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.DeviceConfigurationFeature.DeviceConfigurationFeatureEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.DeviceConfiguration.DeviceConfigurationEntity", "DeviceConfiguration")
                        .WithMany("DeviceConfigurationFeatures")
                        .HasForeignKey("DeviceConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceConfiguration");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.DeviceConfigurationInput.DeviceConfigurationInputEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.DeviceConfiguration.DeviceConfigurationEntity", "DeviceConfiguration")
                        .WithMany("DeviceConfigurationInputs")
                        .HasForeignKey("DeviceConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceConfiguration");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.DeviceConfigurationOutput.DeviceConfigurationOutputEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.DeviceConfiguration.DeviceConfigurationEntity", "DeviceConfiguration")
                        .WithMany("DeviceConfigurationOutputs")
                        .HasForeignKey("DeviceConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceConfiguration");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Event.EventEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.EventImage.EventImageEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Event.EventEntity", "Event")
                        .WithMany("EventImages")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.EventInvite.EventInviteEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Event.EventEntity", "Event")
                        .WithMany("EventInvites")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.EventUser.EventUserEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Autopilot.AutopilotEntity", "Autopilot")
                        .WithMany()
                        .HasForeignKey("AutopilotId");

                    b.HasOne("RazManager.Repository.Stores.Entities.Event.EventEntity", "Event")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazManager.Repository.Stores.Entities.EventUser.EventUserEntity", "EventUser")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventUserId");

                    b.HasOne("RazManager.Repository.Stores.Entities.User.UserEntity", "User")
                        .WithMany("EventUsers")
                        .HasForeignKey("UserId");

                    b.Navigation("Autopilot");

                    b.Navigation("Event");

                    b.Navigation("EventUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.EventUserImage.EventUserImageEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.EventUser.EventUserEntity", "EventUser")
                        .WithMany("EventUserImages")
                        .HasForeignKey("EventUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventUser");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Heat.HeatEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Race.RaceEntity", "Race")
                        .WithMany("Heats")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.HeatIndicator.HeatIndicatorEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Car.CarEntity", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("RazManager.Repository.Stores.Entities.EventUser.EventUserEntity", "EventUser")
                        .WithMany()
                        .HasForeignKey("EventUserId");

                    b.HasOne("RazManager.Repository.Stores.Entities.Heat.HeatEntity", "Heat")
                        .WithMany("HeatIndicators")
                        .HasForeignKey("HeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("EventUser");

                    b.Navigation("Heat");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.HeatIndicatorStint.HeatIndicatorStintEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.EventUser.EventUserEntity", "EventUser")
                        .WithMany()
                        .HasForeignKey("EventUserId");

                    b.HasOne("RazManager.Repository.Stores.Entities.HeatIndicator.HeatIndicatorEntity", "HeatIndicator")
                        .WithMany("HeatIndicatorStints")
                        .HasForeignKey("HeatIndicatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventUser");

                    b.Navigation("HeatIndicator");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.HeatJournal.HeatJournalEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Heat.HeatEntity", "Heat")
                        .WithMany("HeatJournals")
                        .HasForeignKey("HeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heat");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.PointsScheme.PointsSchemeEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.PointsSchemePosition.PointsSchemePositionEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.PointsScheme.PointsSchemeEntity", "PointsScheme")
                        .WithMany("PointsSchemePositions")
                        .HasForeignKey("PointsSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PointsScheme");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Race.RaceEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Event.EventEntity", "Event")
                        .WithMany("Races")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazManager.Repository.Stores.Entities.PointsScheme.PointsSchemeEntity", "PointsScheme")
                        .WithMany()
                        .HasForeignKey("PointsSchemeId");

                    b.HasOne("RazManager.Repository.Stores.Entities.TrackConfiguration.TrackConfigurationEntity", "TrackConfiguration")
                        .WithMany("Races")
                        .HasForeignKey("TrackConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("PointsScheme");

                    b.Navigation("TrackConfiguration");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.RaceCarTag.RaceCarTagEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.CarTag.CarTagEntity", "CarTag")
                        .WithMany()
                        .HasForeignKey("CarTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazManager.Repository.Stores.Entities.Race.RaceEntity", "Race")
                        .WithMany("RaceCarTags")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarTag");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.RaceEventUser.RaceEventUserEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Car.CarEntity", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("RazManager.Repository.Stores.Entities.EventUser.EventUserEntity", "EventUser")
                        .WithMany()
                        .HasForeignKey("EventUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazManager.Repository.Stores.Entities.Race.RaceEntity", "Race")
                        .WithMany("RaceEventUsers")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("EventUser");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.RaceIndicator.RaceIndicatorEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Car.CarEntity", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("RazManager.Repository.Stores.Entities.Race.RaceEntity", "Race")
                        .WithMany("RaceIndicators")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.RaceIndicatorEventUser.RaceIndicatorEventUserEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Car.CarEntity", "Car")
                        .WithMany()
                        .HasForeignKey("CarId");

                    b.HasOne("RazManager.Repository.Stores.Entities.EventUser.EventUserEntity", "EventUser")
                        .WithMany()
                        .HasForeignKey("EventUserId");

                    b.HasOne("RazManager.Repository.Stores.Entities.Race.RaceEntity", "Race")
                        .WithMany("RaceIndicatorEventUsers")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("EventUser");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TenantImage.TenantImageEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", "Tenant")
                        .WithMany("TenantImages")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TenantInvite.TenantInviteEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", "Tenant")
                        .WithMany("TenantInvites")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TenantUser.TenantUserEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", "Tenant")
                        .WithMany("TenantUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazManager.Repository.Stores.Entities.User.UserEntity", "User")
                        .WithMany("TenantUsers")
                        .HasForeignKey("UserId");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Track.TrackEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackConfiguration.TrackConfigurationEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Track.TrackEntity", "Track")
                        .WithMany("TrackConfigurations")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackConfigurationDeviceConfiguration.TrackConfigurationDeviceConfigurationEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.DeviceConfiguration.DeviceConfigurationEntity", "DeviceConfiguration")
                        .WithMany("TrackConfigurationDeviceConfigurations")
                        .HasForeignKey("DeviceConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RazManager.Repository.Stores.Entities.TrackConfiguration.TrackConfigurationEntity", "TrackConfiguration")
                        .WithMany("TrackConfigurationDeviceConfigurations")
                        .HasForeignKey("TrackConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceConfiguration");

                    b.Navigation("TrackConfiguration");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackConfigurationIndicator.TrackConfigurationIndicatorEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.TrackConfiguration.TrackConfigurationEntity", "TrackConfiguration")
                        .WithMany("TrackConfigurationIndicators")
                        .HasForeignKey("TrackConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackConfiguration");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackConfigurationRaceFormat.TrackConfigurationRaceFormatEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.TrackConfiguration.TrackConfigurationEntity", "TrackConfiguration")
                        .WithMany("TrackConfigurationRaceFormats")
                        .HasForeignKey("TrackConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackConfiguration");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackImage.TrackImageEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Track.TrackEntity", "Track")
                        .WithMany("TrackImages")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.UserImage.UserImageEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.User.UserEntity", "User")
                        .WithMany("UserImages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.VersionNote.VersionNoteEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Version.VersionEntity", "Version")
                        .WithMany("VersionNotes")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.VersionPlatform.VersionPlatformEntity", b =>
                {
                    b.HasOne("RazManager.Repository.Stores.Entities.Version.VersionEntity", "Version")
                        .WithMany("VersionPlatforms")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Version");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Autopilot.AutopilotEntity", b =>
                {
                    b.Navigation("AutopilotImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Car.CarEntity", b =>
                {
                    b.Navigation("CarCarTags");

                    b.Navigation("CarImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.CarTag.CarTagEntity", b =>
                {
                    b.Navigation("CarCarTags");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Device.DeviceEntity", b =>
                {
                    b.Navigation("DeviceConfigurations");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.DeviceConfiguration.DeviceConfigurationEntity", b =>
                {
                    b.Navigation("DeviceConfigurationFeatures");

                    b.Navigation("DeviceConfigurationInputs");

                    b.Navigation("DeviceConfigurationOutputs");

                    b.Navigation("TrackConfigurationDeviceConfigurations");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Event.EventEntity", b =>
                {
                    b.Navigation("EventImages");

                    b.Navigation("EventInvites");

                    b.Navigation("EventUsers");

                    b.Navigation("Races");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.EventUser.EventUserEntity", b =>
                {
                    b.Navigation("EventUserImages");

                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Heat.HeatEntity", b =>
                {
                    b.Navigation("HeatIndicators");

                    b.Navigation("HeatJournals");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.HeatIndicator.HeatIndicatorEntity", b =>
                {
                    b.Navigation("HeatIndicatorStints");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.PointsScheme.PointsSchemeEntity", b =>
                {
                    b.Navigation("PointsSchemePositions");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Race.RaceEntity", b =>
                {
                    b.Navigation("Heats");

                    b.Navigation("RaceCarTags");

                    b.Navigation("RaceEventUsers");

                    b.Navigation("RaceIndicatorEventUsers");

                    b.Navigation("RaceIndicators");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Tenant.TenantEntity", b =>
                {
                    b.Navigation("TenantImages");

                    b.Navigation("TenantInvites");

                    b.Navigation("TenantUsers");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Track.TrackEntity", b =>
                {
                    b.Navigation("TrackConfigurations");

                    b.Navigation("TrackImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.TrackConfiguration.TrackConfigurationEntity", b =>
                {
                    b.Navigation("Races");

                    b.Navigation("TrackConfigurationDeviceConfigurations");

                    b.Navigation("TrackConfigurationIndicators");

                    b.Navigation("TrackConfigurationRaceFormats");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.User.UserEntity", b =>
                {
                    b.Navigation("EventUsers");

                    b.Navigation("TenantUsers");

                    b.Navigation("UserImages");
                });

            modelBuilder.Entity("RazManager.Repository.Stores.Entities.Version.VersionEntity", b =>
                {
                    b.Navigation("VersionNotes");

                    b.Navigation("VersionPlatforms");
                });
#pragma warning restore 612, 618
        }
    }
}
