//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RazManager.Repository.Stores.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RazManager.Repository.Stores.Utilities.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already another car with the same name..
        /// </summary>
        internal static string CarNameDuplicate {
            get {
                return ResourceManager.GetString("CarNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already another car tag with the same name..
        /// </summary>
        internal static string CarTagNameDuplicate {
            get {
                return ResourceManager.GetString("CarTagNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device input {0} cannot have an id..
        /// </summary>
        internal static string DeviceDeviceInputDeviceInputIdNone {
            get {
                return ResourceManager.GetString("DeviceDeviceInputDeviceInputIdNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device input {0} requires an id..
        /// </summary>
        internal static string DeviceDeviceInputDeviceInputIdRequired {
            get {
                return ResourceManager.GetString("DeviceDeviceInputDeviceInputIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are (at least) one duplicate configuration of Device input type and Device input id..
        /// </summary>
        internal static string DeviceDeviceInputDuplicate {
            get {
                return ResourceManager.GetString("DeviceDeviceInputDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device output {0} cannot have an id..
        /// </summary>
        internal static string DeviceDeviceOutputDeviceOutputIdNone {
            get {
                return ResourceManager.GetString("DeviceDeviceOutputDeviceOutputIdNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device output {0} requires an id..
        /// </summary>
        internal static string DeviceDeviceOutputDeviceOutputIdRequired {
            get {
                return ResourceManager.GetString("DeviceDeviceOutputDeviceOutputIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are (at least) one duplicate configuration of Device output type and device output id..
        /// </summary>
        internal static string DeviceDeviceOutputDuplicate {
            get {
                return ResourceManager.GetString("DeviceDeviceOutputDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already another device with the same name..
        /// </summary>
        internal static string DeviceNameDuplicate {
            get {
                return ResourceManager.GetString("DeviceNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already a part of the event associated with this invitation code..
        /// </summary>
        internal static string EventInviteExistingUser {
            get {
                return ResourceManager.GetString("EventInviteExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already another event with the same name..
        /// </summary>
        internal static string EventNameDuplicate {
            get {
                return ResourceManager.GetString("EventNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already another stint that starts on the same lap..
        /// </summary>
        internal static string HeatIndicatorStintLapDuplicate {
            get {
                return ResourceManager.GetString("HeatIndicatorStintLapDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This invitation code is not valid..
        /// </summary>
        internal static string InvitationCodeNotValid {
            get {
                return ResourceManager.GetString("InvitationCodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already member of the club/place associated with this invitation code..
        /// </summary>
        internal static string TenantInviteExistingUser {
            get {
                return ResourceManager.GetString("TenantInviteExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A club/place needs to have at least one administrator..
        /// </summary>
        internal static string TenantUserAdministratorRequired {
            get {
                return ResourceManager.GetString("TenantUserAdministratorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track configurations cannot have the same name..
        /// </summary>
        internal static string TrackConfigurationNameDuplicate {
            get {
                return ResourceManager.GetString("TrackConfigurationNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already another track with the same name..
        /// </summary>
        internal static string TrackNameDuplicate {
            get {
                return ResourceManager.GetString("TrackNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username has already signed up..
        /// </summary>
        internal static string UserAlreadySignedUp {
            get {
                return ResourceManager.GetString("UserAlreadySignedUp", resourceCulture);
            }
        }
    }
}
